<?php


function output_header_navigation($title, $common_css_indicator){
    echo '<!DOCTYPE html>';
    echo '<html lang="en">';
    echo '';
    echo '<head>';
    echo '<title>SMAPPLE - '. $title .'</title>';
    echo '<meta charset="utf-8">';
    echo '<meta name="viewport" content="width=device-width, initial-scale=1">';
    echo '';
    echo '<link rel="apple-touch-icon" href="assets/img/apple-icon.png">';
    echo '<link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico">';
    echo '';
    if ($common_css_indicator == "min_custom") {
        echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css" />';
        echo '<link rel="stylesheet" href="assets/css/bootstrap-custom.css" />';

    } elseif($common_css_indicator == "min_custom_index"){
        echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css" />';
        echo '<link rel="stylesheet" href="assets/css/bootstrap-custom.css" />';
        echo '<link rel="stylesheet" href="assets/css/index.css " />';
        
    } elseif($common_css_indicator == "min_custom_custom"){
        echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css" />';
        echo '<link rel="stylesheet" href="assets/css/bootstrap-custom.css" />';
        echo '<link rel="stylesheet" href="assets/css/custom.css " />';
        echo '';

    } else{
        echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css" />';
        echo '<link rel="stylesheet" href="assets/css/bootstrap-custom.css" />';
        echo '<link rel="stylesheet" href="assets/css/custom.css" />';
        echo '<link rel="stylesheet" href="assets/css/stylereg.css" />';
        
    }
    echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css">';
    echo '<link rel="stylesheet" href="assets/css/bootstrap-custom.css">';
    echo '';
    echo '<!-- Load fonts style after rendering the layout styles -->';
    echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap">';
    echo '<link rel="stylesheet" href="assets/css/fontawesome.min.css">';
    echo '';
    echo '';
    echo '</head>';
    echo '';
    echo '<body>';
    echo '<nav class="navbar navbar-expand-lg navbar-light shadow">';
    echo '<div class="container d-flex justify-content-between align-items-center">';
    echo '<a class="navbar-brand logo h1 align-self-center" href="home.php">';
    echo '<img src="assets/img/SMAPPLE.png" height="90" alt="Logo">';
    echo '</a>';
    echo '';
    echo '<button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
    echo '<span class="navbar-toggler-icon"></span>';
    echo '</button>';
    echo '';
    echo '<div class="align-self-center collapse navbar-collapse flex-fill d-lg-flex justify-content-lg-between" id="main_nav">';
    echo '';
    echo '<div class="flex-fill">';
    echo '<ul class="nav navbar-nav d-flex justify-content-center mx-lg-auto">';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="home.php">Home</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="about.php">About</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="login.php">Login</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="register.php">Register</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="profile.php" style="margin-right: 20px">Profile</a>';
    echo '</li>';
    echo '</ul>';
    echo '</div>';
    echo '<div class="navbar align-self-center d-flex">';
    echo '';
    echo '<!-- Button trigger modal -->';
    echo '<a class="nav-icon position-relative text-decoration-none" href="carts_summary.php">';
    echo '<i class="fa fa-fw fa-cart-arrow-down text-dark mr-1" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"></i>';
    echo '';
    echo '</a>';
    echo '';
    echo '';
    echo '</div>';
    echo '</div>';
    echo '</div>';
    echo '</nav>';
    echo '<!-- Close Header -->';
}

function output_footer(){
    echo '<!-- Start Footer -->';
    echo '<footer class="bg-dark" id="footer">';
    echo '<div class="container">';
    echo '<div class="row">';
    echo '<div class="col-md-4 pt-5">';
    echo '<h2 class="h2 text-light border-bottom pb-3 border-light logo">';
    echo 'SMAPPLE';
    echo '</h2>';
    echo '<ul class="list-unstyled text-light footer-link-list">';
    echo '<li>';
    echo '<i class="fas fa-map-marker-alt fa-fw"></i> Middlesex University, Dubai';
    echo '</li>';
    echo '<li>';
    echo '<i class="fa fa-phone fa-fw"></i>';
    echo '<a class="text-decoration-none">04 2132 043924</a';
    echo '>';
    echo '</li>';
    echo '<li>';
    echo '<i class="fa fa-envelope fa-fw"></i>';
    echo '<a class="text-decoration-none"';
    echo '>sdsa@live.mdx.ac.uk</a';
    echo '>';
    echo '</li>';
    echo '</ul>';
    echo '</div>';
    echo '';
    echo '<div class="col-md-4 pt-5">';
    echo '<h2 class="h2 text-light border-bottom pb-3 border-light">';
    echo 'Assistance';
    echo '</h2>';
    echo '<ul class="list-unstyled text-light footer-link-list">';
    echo '<li><a class="text-decoration-none" href="#">Sell at SMAPPLE.com</a></li>';
    echo '<li><a class="text-decoration-none" href="#">Store Locator</a></li>';
    echo '<li><a class="text-decoration-none" href="#">Bulk Orders & Enquiries</a></li>';
    echo '<li>';
    echo '<a class="text-decoration-none" href="#">Easy Payment Plan</a>';
    echo '</li>';
    echo '<li>';
    echo '<a class="text-decoration-none" href="#">Disclaimer Policy</a>';
    echo '</li>';
    echo '</ul>';
    echo '</div>';
    echo '';
    echo '<div class="col-md-4 pt-5">';
    echo '<h2 class="h2 text-light border-bottom pb-3 border-light">';
    echo 'Further Info';
    echo '</h2>';
    echo '<ul class="list-unstyled text-light footer-link-list">';
    echo '<li><a class="text-decoration-none" href="#">Home</a></li>';
    echo '<li><a class="text-decoration-none" href="#">About Us</a></li>';
    echo '<li>';
    echo '<a class="text-decoration-none" href="#">Shop Locations</a>';
    echo '</li>';
    echo '<li><a class="text-decoration-none" href="#">FAQs</a></li>';
    echo '<li><a class="text-decoration-none" href="#">Contact</a></li>';
    echo '</ul>';
    echo '</div>';
    echo '</div>';
    echo '';
    echo '</div>';
    echo '';
    echo '<div class="w-100 bg-black py-3">';
    echo '<div class="container">';
    echo '<div class="row pt-2">';
    echo '<div class="col-12">';
    echo '<p class="text-left text-light">';
    echo 'Copyright &copy; 2021 SMAPPLE | Designed by Team SMAPPLE';
    echo '</p>';
    echo '</div>';
    echo '</div>';
    echo '</div>';
    echo '</div>';
    echo '</footer>';
    echo '<!-- End Footer -->';
    echo '<!-- Start Script -->';
    echo '<script src="assets/js/bootstrap.bundle.min.js"></script>';
    echo '<script src="assets/js/custom.js"></script>';
    echo '<!-- End Script -->';
}

function output_admin_navigation($title){
    echo '<!DOCTYPE html>';
    echo '<html lang="en">';
    echo '';
    echo '<head>';
    echo '<title>SMAPPLE - Admin '. $title .' </title>';
    echo '<meta charset="utf-8" />';
    echo '<meta name="viewport" content="width=device-width, initial-scale=1" />';
    echo '';
    echo '<link rel="shortcut icon" type="image/x-icon" href="assets/img/favicon.ico" />';
    echo '';
    echo '<link rel="stylesheet" href="assets/css/bootstrap.min.css" />';
    echo '<link rel="stylesheet" href="assets/css/bootstrap-custom.css" />';
    echo '';
    echo '';
    echo '<!-- Font -->';
    echo '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap" />';
    echo '';
    echo '<!-- Icons -->';
    echo '<link rel="stylesheet" href="assets/css/fontawesome.min.css" />';
    echo '</head>';
    echo '';
    echo '<body>';
    echo '<!-- Header -->';
    echo '<nav class="navbar navbar-expand-lg navbar-light shadow">';
    echo '<div class="container d-flex justify-content-between align-items-center">';
    echo '<a class="navbar-brand logo h1 align-self-center" href="home.php">';
    echo '<img src="assets/img/SMAPPLE.png" height="90" alt="Logo">';
    echo '</a>';
    echo '';
    echo '<button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">';
    echo '<span class="navbar-toggler-icon"></span>';
    echo '</button>';
    echo '';
    echo '<div class="align-self-center collapse navbar-collapse flex-fill d-lg-flex justify-content-lg-between" id="main_nav">';
    echo '<div class="flex-fill">';
    echo '<ul class="nav navbar-nav d-flex justify-content-center mx-lg-auto">';
    echo '';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="view_products_admin.php" style="margin-left: -20px">View Products</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="add_products_admin.php">Add Products</a>';
    echo '</li>';
    echo '<li class="nav-item">';
    echo '<a class="nav-link" href="view_order_admin.php">View Orders</a>';
    echo '</li>';
    echo '</ul>';
    echo '</div>';
    echo '<div class="navbar align-self-center d-flex">';
    echo '';
    echo '</div>';
    echo '</div>';
    echo '</div>';
    echo '</nav>';
    echo '<!-- Close Header -->';
}
